import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontSize: {

        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-h1": ["36px", {"lineHeight": "1.3", "fontWeight": "700"}],
        "display-lg": ["48px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-h3": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "headline-h2": ["28px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "code": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "display-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
      },
      spacing: {

        "stack-lg": "3rem",
        "stack-md": "1.5rem",
        "stack-sm": "0.5rem",
        "margin-mobile": "1rem",
        "container-max": "1280px",
        "margin-desktop": "2.5rem",
        "gutter": "1.5rem",
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "label-caps": ["Inter"],
        "headline-h1": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "body-md": ["Inter"],
        "headline-h3": ["Inter"],
        "headline-h2": ["Playfair Display"],
        "body-lg": ["Inter"],
        "code": ["JetBrains Mono"],
        "display-lg-mobile": ["Playfair Display"],
        "display-bold": ["Space Grotesk", "sans-serif"],

        serif: ["Times New Roman", "Times", "Georgia", "serif"],
        sans: ["-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
      },
      colors: {
        "on-tertiary": "#ffffff",
        "primary-fixed": "#dae2fd",
        "on-tertiary-fixed-variant": "#3a485c",
        "surface-bright": "#fcf8fa",
        "on-secondary": "#ffffff",
        "secondary-container": "#e21e49",
        "error-container": "#ffdad6",
        "example-amber": "#FFFBEB",
        "primary-fixed-dim": "#bec6e0",
        "on-background": "#1b1b1d",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f3f0f2",
        "tertiary-fixed": "#d5e3fd",
        "theorem-blue": "#EFF6FF",
        "primary-container": "#131b2e",
        "surface-container-low": "#f6f3f5",
        "surface-container": "#f0edef",
        "on-secondary-container": "#fffbff",
        "on-tertiary-fixed": "#0d1c2f",
        "on-tertiary-container": "#76859b",
        "on-secondary-fixed": "#40000c",
        "inverse-primary": "#bec6e0",
        "on-primary-container": "#7c839b",
        "on-surface-variant": "#45464d",
        "outline-variant": "#c6c6cd",
        "intermediate-yellow": "#F59E0B",
        "surface-container-high": "#eae7e9",
        "error": "#ba1a1a",
        "on-surface": "#1b1b1d",
        "surface-dim": "#dcd9db",
        "surface-variant": "#e4e2e4",
        "surface": "#fcf8fa",
        "outline": "#76777d",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e4e2e4",
        "tertiary-container": "#0d1c2f",
        "secondary-fixed": "#ffdada",
        "on-secondary-fixed-variant": "#920028",
        "tertiary": "#000000",
        "on-primary-fixed": "#131b2e",
        "on-primary-fixed-variant": "#3f465c",
        "secondary-fixed-dim": "#ffb3b6",
        "on-primary": "#ffffff",
        "beginner-green": "#22C55E",
        "inverse-surface": "#303032",
        "advanced-red": "#EF4444",
        "surface-tint": "#565e74",
        "tertiary-fixed-dim": "#b9c7e0",
        "definition-slate": "#F8FAFC",
        "on-error": "#ffffff",

        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        hero: {
          dark: "hsl(var(--hero-dark))",
          mid: "hsl(var(--hero-mid))",
          light: "hsl(var(--hero-light))",
        },
        definition: {
          bg: "hsl(var(--definition-bg))",
          border: "hsl(var(--definition-border))",
        },
        theorem: {
          bg: "hsl(var(--theorem-bg))",
          border: "hsl(var(--theorem-border))",
        },
        example: {
          bg: "hsl(var(--example-bg))",
          border: "hsl(var(--example-border))",
        },
        warning: {
          bg: "hsl(var(--warning-bg))",
          border: "hsl(var(--warning-border))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        float: {
          "0%": { transform: "translateY(100vh) rotate(0deg)", opacity: "0" },
          "10%": { opacity: "0.8" },
          "90%": { opacity: "0.8" },
          "100%": { transform: "translateY(-100vh) rotate(360deg)", opacity: "0" },
        },
        "fade-in-up": {
          from: { opacity: "0", transform: "translateY(30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { left: "-100%" },
          "100%": { left: "100%" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        float: "float 15s infinite linear",
        "fade-in-up": "fade-in-up 1s ease-out forwards",
        shimmer: "shimmer 0.5s forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;